apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8081'
  labels:
    app: cypress-prometheus-exporter
  name: cypress-prometheus-exporter
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: cypress-prometheus-exporter
status:
  loadBalancer: {}
